name: CI/CD pipeline for BobApp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Compile code
      run: mvn clean compile
    - name: Run tests
      run: mvn test
    - name: Package application
      run: mvn package -DskipTests
    - name: Generate Jacoco coverage report
      run: mvn jacoco:report
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: back/target/site/jacoco/
    - name: Upload backend target directory
      uses: actions/upload-artifact@v4
      with:
        name: backend-build-temp
        path: back/target/classes
    - name: Generate classpath file
      run: mvn dependency:build-classpath -Dmdep.outputFile=target/classpath.txt
    - name: Upload classpath artifact
      uses: actions/upload-artifact@v4
      with:
        name: backend-classpath
        path: back/target/classpath.txt

  frontend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'
        cache-dependency-path: front/package-lock.json
    - name: Fetch dependencies
      run: npm ci
    - name: Run tests and coverage
      run: npm test -- --code-coverage --watch=false --browsers=ChromeHeadless
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: angular-coverage-report
        path: front/coverage/bobapp

  sonar-quality:
    name: SonarCloud analysis
    runs-on: ubuntu-latest
    needs: [backend-build-and-test, frontend-test]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: front/package-lock.json

      - name: Download backend classpath
        uses: actions/download-artifact@v4
        with:
          name: backend-classpath
          path: back/target
 
      - name: Set sonar.java.libraries property
        run: echo "sonar.java.libraries=$(cat back/target/classpath.txt | tr ':' ',')" >> sonar-project.properties

      - name: Download backend-build-temp
        uses: actions/download-artifact@v4
        with:
          name: backend-build-temp
          path: back/target/classes

      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: jacoco-report
          path: back/target/site/jacoco/

      - name: Download frontend coverage report
        uses: actions/download-artifact@v4
        with:
          name: angular-coverage-report
          path: front/coverage/bobapp

      - name: SonarCloud scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Wait for Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Delete backend-build-temp
        uses: geekyeggo/delete-artifact@v5
        with:
          name: backend-build-temp

      - name: Delete backend-classpath
        uses: geekyeggo/delete-artifact@v5
        with:
          name: backend-classpath

  docker-build-push:
    name: Build and push Docker images
    runs-on: ubuntu-latest
    needs: [sonar-quality]
    if: github.event_name == 'push' && success()
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./back
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-back:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./front
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-front:latest

