name: CI/CD pipeline for BobApp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-build-and-test:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    # - name: Build with Maven
    #   run: mvn -B package --file pom.xml
    - name: Compile code
      run: mvn clean compile
    - name: Run tests
      run: mvn test
    - name: Package application
      run: mvn package -DskipTests
    - name: Generate Jacoco coverage report
      run: mvn jacoco:report
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: back/target/site/jacoco/

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
      # uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
